topics = ["telegraf_*"]
batch_size = 5000

[influxdb]
host = "http://influxdb:8086"
precision = "s"

[[mapping]]
onetopic                             = "generic"
[[mapping]]
anothertopic                         = "generic"
[[mapping]]
"*pgsql*"                            = "dbms"
[[mapping]]
"*webmail*"                          = "web"
[[mapping]]
"*"                                  = "generic"

[kafka]
brokers = ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
client_id = "kafka2influx1"
consumer_group = "kafka2influx-cg"
version = "0.10.1.1"
format = "json"

