topics = ["telegraf_*"]
batch_size = 5000

[influxdb]
host = "http://influxdb:8086"
auth = false
username = ""
password = ""
precision = "s"

[databases]
telegraf_onetopic                    = "generic"
telegraf_anothertopic                = "generic"
telegraf_pgsql                       = "dbms"
telegraf_mysql                       = "dbms"
telegraf_ldap                        = "dbms"
telegraf_webmail                     = "web"
telegraf_vmail                       = "mail"
telegraf_photoapp                    = "web"
default                              = "generic"

[kafka]
brokers = ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
client_id = "kafka2influx1"
consumer_group = "kafka2influx-cg"
version = "0.10.1.1"
format = "json"

